# 服务配置
server:
  port: ${SERVER_PORT:30000}

# 应用配置
spring:
  application:
    name: ${APPLICATION_NAME:spring-cloud-gateway}
  cloud:
    gateway:
      # 路由规则
      routes:
        # 路由ID，唯一
        - id: spring-cloud-system
          # 目标URL，路由到微服务的地址
          uri: lb://spring-cloud-system
          # 断言（判断条件）
          predicates:
            # 匹配对应URL的请求，将匹配到的请求追加到目标URI之后
            - Path=/system/**
# Eureka 配置
eureka:
  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: ${LEASE_RENEWAL_INTERVAL_IN_SECONDS:30}
  client:
    fetch-registry: ${FETCH_REGISTRY:true}
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://admin:123456@spring-cloud-eureka-master:8761/eureka/,http://admin:123456@spring-cloud-eureka-slave:8762/eureka/}